# Análise da Bilhetagem - Outliers Anomalias e Padrões

## Organização da Base Histórica (2015-2018) por Linha/Estação/Dia

In [1]:
#Bibliotecas
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import glob

In [2]:
#Leitura dos dados da série histórica
arquivosDados = glob.glob('dados\Embarques por Faixa Horaria por Linha*')
dados = []
for dia in arquivosDados:
    esteDia = pd.read_pickle(dia)
    dados.append(esteDia)
dados = pd.concat(dados)
del dados['sistema']

In [3]:
#Quantidade de registros e características gerais
len(dados)

1296003

In [4]:
dados.head()

total_dia       dia     0     1   2    3     4      5      6  \
linha_blt                                                                 
1015-10        169.0  20160101   NaN   NaN NaN  NaN   NaN    4.0    7.0   
1016-10       2221.0  20160101  20.0   3.0 NaN  NaN   NaN   20.0   97.0   
1017-10       4537.0  20160101  55.0  21.0 NaN  6.0  64.0  138.0  163.0   
1018-10       1287.0  20160101  13.0   NaN NaN  NaN   7.0   45.0   68.0   
1021-10          5.0  20160101   5.0   NaN NaN  NaN   NaN    NaN    NaN   

               7  ...      14     15     16     17     18     19     20  \
linha_blt         ...                                                     
1015-10      5.0  ...     8.0   14.0    6.0   15.0   14.0   17.0    5.0   
1016-10     76.0  ...   162.0  155.0  166.0  106.0  185.0  151.0  117.0   
1017-10    160.0  ...   329.0  361.0  310.0  368.0  164.0  156.0  304.0   
1018-10     51.0  ...    65.0   59.0   88.0   87.0   94.0   98.0   65.0   
1021-10      NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN    NaN   

              21     22    23  
linha_blt                      
1015-10     20.0    1.0   NaN  
1016-10    131.0   71.0  33.0  
1017-10    277.0  118.0  72.0  
1018-10     59.0   27.0  26.0  
1021-10      NaN    NaN   NaN  

[5 rows x 26 columns]

In [5]:
#Classificação do tipo de dia
dias = pd.read_csv("classificacao_dos_dias_2015-2018.csv")
dias['dia'] = dias.dia.astype(str)

dias.head()

dia    formato  mes  dia_semana  du  sab  dom  ferias tipo_dia  \
0  20150101 2015-01-01    1           5   1    0    0       1  feriado   
1  20150102 2015-01-02    1           6   1    0    0       1    ponte   
2  20150103 2015-01-03    1           7   0    1    0       1   normal   
3  20150104 2015-01-04    1           1   0    0    1       1   normal   
4  20150105 2015-01-05    1           2   1    0    0       1   normal   

   feriado  ptes  eventos  
0        1     0        0  
1        0     1        0  
2        0     0        0  
3        0     0        0  
4        0     0        0

In [6]:
#Classificação de sistema (Ônibus/Trilho/CPTM/Metro/Linhas/Bacia)

#pd.DataFrame(np.unique(dados.index.values)).to_excel("linhas.xlsx") #para classificar
#Puxa classificação feita
classe = pd.read_csv("linhas_classificacao_em_tipo.csv")

classe.head()

linha sistema  onibus  noturna  trilhos  metro  cptm linha_trilho  \
0  1012-10  onibus       1        0        0      0     0          NaN   
1  1015-10  onibus       1        0        0      0     0          NaN   
2  1016-10  onibus       1        0        0      0     0          NaN   
3  1017-10  onibus       1        0        0      0     0          NaN   
4  1018-10  onibus       1        0        0      0     0          NaN   

   linha1  linha2                        ...                          area  \
0       0       0                        ...                             1   
1       0       0                        ...                             1   
2       0       0                        ...                             2   
3       0       0                        ...                             1   
4       0       0                        ...                             2   

   area1  area2  area3  area4  area5  area6  area7  area8  \
0      1      0      0      0      0      0      0      0   
1      1      0      0      0      0      0      0      0   
2      0      1      0      0      0      0      0      0   
3      1      0      0      0      0      0      0      0   
4      0      1      0      0      0      0      0      0   

                                         Unnamed: 33  
0  sns.distplot(diaLinha['1012-10'],label='1012-10')  
1  sns.distplot(diaLinha['1015-10'],label='1015-10')  
2  sns.distplot(diaLinha['1016-10'],label='1016-10')  
3  sns.distplot(diaLinha['1017-10'],label='1017-10')  
4  sns.distplot(diaLinha['1018-10'],label='1018-10')  

[5 rows x 34 columns]

In [7]:
dados = pd.merge(dados,classe,how='left',left_index=True,right_on='linha')

dados.head()

total_dia       dia     0     1   2    3     4      5      6      7  \
1      169.0  20160101   NaN   NaN NaN  NaN   NaN    4.0    7.0    5.0   
2     2221.0  20160101  20.0   3.0 NaN  NaN   NaN   20.0   97.0   76.0   
3     4537.0  20160101  55.0  21.0 NaN  6.0  64.0  138.0  163.0  160.0   
4     1287.0  20160101  13.0   NaN NaN  NaN   7.0   45.0   68.0   51.0   
7        5.0  20160101   5.0   NaN NaN  NaN   NaN    NaN    NaN    NaN   

                         ...                          area  area1  area2  \
1                        ...                             1      1      0   
2                        ...                             2      0      1   
3                        ...                             1      1      0   
4                        ...                             2      0      1   
7                        ...                             1      1      0   

   area3  area4  area5  area6  area7  area8  \
1      0      0      0      0      0      0   
2      0      0      0      0      0      0   
3      0      0      0      0      0      0   
4      0      0      0      0      0      0   
7      0      0      0      0      0      0   

                                         Unnamed: 33  
1  sns.distplot(diaLinha['1015-10'],label='1015-10')  
2  sns.distplot(diaLinha['1016-10'],label='1016-10')  
3  sns.distplot(diaLinha['1017-10'],label='1017-10')  
4  sns.distplot(diaLinha['1018-10'],label='1018-10')  
7  sns.distplot(diaLinha['1021-10'],label='1021-10')  

[5 rows x 60 columns]

In [8]:
dados.columns

Index([   'total_dia',          'dia',              0,              1,
                    2,              3,              4,              5,
                    6,              7,              8,              9,
                   10,             11,             12,             13,
                   14,             15,             16,             17,
                   18,             19,             20,             21,
                   22,             23,        'linha',      'sistema',
             'onibus',      'noturna',      'trilhos',        'metro',
               'cptm', 'linha_trilho',       'linha1',       'linha2',
             'linha3',       'linha4',       'linha5',       'linha6',
             'linha7',       'linha8',       'linha9',      'linha10',
            'linha11',      'linha12',      'linha13',      'linha14',
            'linha15',       'preemb',         'area',        'area1',
              'area2',        'area3',        'area4',        'area5',
      

In [9]:
#Junta o tipo de dia
dados = pd.merge(dados,dias,how='left',left_on='dia',right_on='dia')

In [10]:
dados.head()

total_dia       dia     0     1   2    3     4      5      6      7  \
0      169.0  20160101   NaN   NaN NaN  NaN   NaN    4.0    7.0    5.0   
1     2221.0  20160101  20.0   3.0 NaN  NaN   NaN   20.0   97.0   76.0   
2     4537.0  20160101  55.0  21.0 NaN  6.0  64.0  138.0  163.0  160.0   
3     1287.0  20160101  13.0   NaN NaN  NaN   7.0   45.0   68.0   51.0   
4        5.0  20160101   5.0   NaN NaN  NaN   NaN    NaN    NaN    NaN   

    ...     mes  dia_semana  du  sab  dom  ferias  tipo_dia  feriado  ptes  \
0   ...       1           6   1    0    0       1   feriado        1     0   
1   ...       1           6   1    0    0       1   feriado        1     0   
2   ...       1           6   1    0    0       1   feriado        1     0   
3   ...       1           6   1    0    0       1   feriado        1     0   
4   ...       1           6   1    0    0       1   feriado        1     0   

   eventos  
0        0  
1        0  
2        0  
3        0  
4        0  

[5 rows x 71 columns]

In [11]:
dados.groupby('trilhos').get_group(1).to_csv('trilhos_completa.csv')

In [12]:
dados.columns

Index([   'total_dia',          'dia',              0,              1,
                    2,              3,              4,              5,
                    6,              7,              8,              9,
                   10,             11,             12,             13,
                   14,             15,             16,             17,
                   18,             19,             20,             21,
                   22,             23,        'linha',      'sistema',
             'onibus',      'noturna',      'trilhos',        'metro',
               'cptm', 'linha_trilho',       'linha1',       'linha2',
             'linha3',       'linha4',       'linha5',       'linha6',
             'linha7',       'linha8',       'linha9',      'linha10',
            'linha11',      'linha12',      'linha13',      'linha14',
            'linha15',       'preemb',         'area',        'area1',
              'area2',        'area3',        'area4',        'area5',
      

# Análise de Descontinuidade da Fonte dos Dados

In [ ]:
#Descontinuidade
dadosTrilhos = dados.groupby('sistema').get_group('trilhos').copy(deep=True)

maximoDias = np.max(dadosTrilhos.linha.value_counts())

print('Maximo de dias:',maximoDias)
contEstacaoDias = dadosTrilhos.linha.value_counts()
print(contEstacaoDias)

In [ ]:
#Dias faltantes
diasFaltantes = maximoDias-contEstacaoDias

#Remove estações novas e CiaPark
diasFaltantes = diasFaltantes.drop(['HNM - Higienópolis - Mackenzie - Linha 4',
                    'BGA - Borba Gato - METRO L5',
                    'BRK - Brooklin - METRO L5',
                    'ABV - Alto da Boa Vista - METRO L5',
                    'EGL - Eng Goulart - CPTM L12'])
diasFaltantes

In [ ]:
numeroDiasFaltantes = pd.DataFrame(diasFaltantes)
numeroDiasFaltantes.columns = ['numeroDias']
faltantesTrilhos = pd.merge(numeroDiasFaltantes,classe,how='left',left_index=True,right_on='linha')

faltantesTrilhos.groupby('linha_trilho').get_group('Linha 15').groupby(['linha_trilho','linha'])['numeroDias'].sum()

In [ ]:
mediaDiasFaltantesPorLinha = faltantesTrilhos.groupby(['linha_trilho'])['numeroDias'].mean().astype(int)
mediaDiasFaltantesPorLinha

In [ ]:
plt.rcParams.update({'font.size': 16})
mediaDiasFaltantesPorLinha.plot('bar',figsize=(8,6))
plt.xlabel('Linhas Sistema Trilho')
plt.ylabel('Média de Dias Faltantes')
plt.show()

In [ ]:
#Dias faltantes por estação do sistema trilho
print('Dias faltantes por Estação')
plt.rcParams.update({'font.size': 12})
faltantesTrilhos.groupby(['linha_trilho','linha'])['numeroDias'].sum().plot('barh',figsize=(10,50))
plt.xlabel('Média de Dias Faltantes')
plt.ylabel('Linhas Sistema Trilho')
plt.show()

In [19]:
#Marca os dias sem registros para plotar calendário
dadosTrilhosMetro = dadosTrilhos.groupby('metro').get_group(1).copy(deep=True)
dadosTrilhosMetro.head()

total_dia       dia     0     1    2   3      4      5     6     7  \
946       27.0  20160101  16.0  11.0  NaN NaN    NaN    NaN   NaN   NaN   
948     1453.0  20160101  65.0  29.0  1.0 NaN    9.0   44.0  74.0  73.0   
950       78.0  20160101  44.0  30.0  2.0 NaN    2.0    NaN   NaN   NaN   
951      510.0  20160101  18.0  23.0  NaN NaN    5.0   30.0  26.0  14.0   
953     1042.0  20160101   NaN   NaN  NaN NaN  253.0  118.0  48.0  30.0   

      ...     mes  dia_semana  du  sab  dom  ferias  tipo_dia  feriado  ptes  \
946   ...       1           6   1    0    0       1   feriado        1     0   
948   ...       1           6   1    0    0       1   feriado        1     0   
950   ...       1           6   1    0    0       1   feriado        1     0   
951   ...       1           6   1    0    0       1   feriado        1     0   
953   ...       1           6   1    0    0       1   feriado        1     0   

     eventos  
946        0  
948        0  
950        0  
951        0  
953        0  

[5 rows x 71 columns]

In [20]:
estacoesNovas = np.array(['HNM - Higienópolis - Mackenzie - Linha 4',
                    'BGA - Borba Gato - METRO L5',
                    'BRK - Brooklin - METRO L5',
                    'ABV - Alto da Boa Vista - METRO L5',
                    'EGL - Eng Goulart - CPTM L12'])

dadosTrilhosMetroEstacoesVerificar = dadosTrilhosMetro[~dadosTrilhosMetro.linha.isin(estacoesNovas)]

comunicaram = dadosTrilhosMetroEstacoesVerificar.groupby('dia').size()
naoComunicaram = np.max(comunicaram)-comunicaram
naoComunicaram.head()

dia
20160101     4
20160102     4
20160103     3
20160104    15
20160105    61
dtype: int64

In [ ]:
#Gráfico de quando ocorreram as nao comunicações
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import calmap
naoComunicaram.index = pd.to_datetime(naoComunicaram.index)
naoComunicaram[naoComunicaram==0] = np.NaN
calmap.calendarplot(naoComunicaram,fig_kws=dict(figsize=(13, 8)),vmin=0,vmax=8,
                    cmap='hot_r',linewidth=1,linecolor='black',fillcolor='white')

In [ ]:
#Quais não comunicaram em cada dia?
estacoes = np.unique(dadosTrilhosMetro.linha)

#Remove estações novas da verificação
estacoesNovas = np.array(['HNM - Higienópolis - Mackenzie - Linha 4',
                    'BGA - Borba Gato - METRO L5',
                    'BRK - Brooklin - METRO L5',
                    'ABV - Alto da Boa Vista - METRO L5',
                    'EGL - Eng Goulart - CPTM L12'])
estacoesVerificar = np.setdiff1d(estacoes,estacoesNovas)

diasSemComunicacaoDeEstacao = []
diasComComunicacaoTodasEstacoesMetro = []
for dia,dadosDia in dadosTrilhosMetro.groupby('dia'):
    estacoesDesteDia = np.unique(dadosDia.linha)
    estacoesSemComunicacao = np.setdiff1d(estacoesVerificar,estacoesDesteDia)
    print(dia,estacoesSemComunicacao)
    if len(estacoesSemComunicacao)>=1:
        diasSemComunicacaoDeEstacao.append(dia)
    else:
        diasComComunicacaoTodasEstacoesMetro.append(dia)

print(diasSemComunicacaoDeEstacao)

# Estações com Baixa Demanda : Anomalia e Outliers nos Trilhos

### Premissas

Remover da base original de todos os dias, aqueles dias que tiveram ao menos uma estação do sistema de Metrô com falta de comunicação. 

Partindo do princípio que este sistema é o mais importante na análise do sistema da cidade de SP e que todas as estações devem comunicar, já que todas as estações são importantes na rede.

_Para analisar anomalias/outliers de demanda, selecionar apenas dias ÚTEIS, não-feriados, não-eventos, não-férias, não-pontes e com TODAS as estações de Metrô comunicando._


In [23]:
dados.head()

total_dia       dia     0     1   2    3     4      5      6      7  \
0      169.0  20160101   NaN   NaN NaN  NaN   NaN    4.0    7.0    5.0   
1     2221.0  20160101  20.0   3.0 NaN  NaN   NaN   20.0   97.0   76.0   
2     4537.0  20160101  55.0  21.0 NaN  6.0  64.0  138.0  163.0  160.0   
3     1287.0  20160101  13.0   NaN NaN  NaN   7.0   45.0   68.0   51.0   
4        5.0  20160101   5.0   NaN NaN  NaN   NaN    NaN    NaN    NaN   

    ...     mes  dia_semana  du  sab  dom  ferias  tipo_dia  feriado  ptes  \
0   ...       1           6   1    0    0       1   feriado        1     0   
1   ...       1           6   1    0    0       1   feriado        1     0   
2   ...       1           6   1    0    0       1   feriado        1     0   
3   ...       1           6   1    0    0       1   feriado        1     0   
4   ...       1           6   1    0    0       1   feriado        1     0   

   eventos  
0        0  
1        0  
2        0  
3        0  
4        0  

[5 rows x 71 columns]

In [24]:
#Dias uteis validos (comunicacao de todas as estacoes de Metrô, dias úteis, não-férias, não-feriados, não-pontes, não-eventos)
duv = dados[(~dados.dia.isin(diasSemComunicacaoDeEstacao)) &
            (dados.du==1) &
            (dados.ferias==0) & 
            (dados.feriado==0) & 
            (dados.ptes==0) & 
            (dados.eventos==0)]

print(len(duv),'registros')
diasValidos = np.unique(duv.dia) 
print(len(diasValidos),'dias úteis válidos para análise de outliers')

diasValidos

448192 registros
300 dias úteis válidos para análise de outliers


array(['20160517', '20160518', '20160519', '20160520', '20160523',
       '20160524', '20160525', '20160530', '20160531', '20160601',
       '20160602', '20160603', '20160606', '20160607', '20160608',
       '20160609', '20160610', '20160613', '20160614', '20160615',
       '20160616', '20160617', '20160620', '20160621', '20160622',
       '20160623', '20160624', '20160627', '20160628', '20160629',
       '20160630', '20160801', '20160802', '20160803', '20160804',
       '20160805', '20160808', '20160809', '20160810', '20160811',
       '20160812', '20160815', '20160816', '20160817', '20160818',
       '20160819', '20160822', '20160823', '20160824', '20160825',
       '20160826', '20160829', '20160830', '20160831', '20160901',
       '20160902', '20160905', '20160906', '20160908', '20160909',
       '20160912', '20160913', '20160914', '20160915', '20160916',
       '20160919', '20160920', '20160921', '20160922', '20160923',
       '20160926', '20160927', '20160928', '20160929', '201609

In [25]:
diaLinha = pd.pivot_table(duv,index=['dia'],values=['total_dia'],columns=['linha'],aggfunc=np.sum)
diaLinha.columns = diaLinha.columns.droplevel()

diaLinha.columns

Index(['1012-10', '1015-10', '1016-10', '1017-10', '1018-10', '1019-10',
       '1020-10', '1021-10', '1024-10', '1025-10',
       ...
       'VCL - Vila Clarice - CPTM L7', 'VGO - Vergueiro - METRO L1',
       'VMD - Vila Madalena - METRO L2', 'VMN - Vila Mariana - METRO L1',
       'VOL - Vila Olimpia - CPTM L9',
       'VPA - Guilhermina Esperanca - METRO L3',
       'VPL - Vßrzea Paulista - CPTM L7', 'VPR - Vila Prudente - METRO L2',
       'VPT - Vila Prudente - METRO L15', 'VTD - Vila Matilde - METRO L3'],
      dtype='object', name='linha', length=1606)

In [ ]:
diaLinha

In [27]:
diaLinha.columns

Index(['1012-10', '1015-10', '1016-10', '1017-10', '1018-10', '1019-10',
       '1020-10', '1021-10', '1024-10', '1025-10',
       ...
       'VCL - Vila Clarice - CPTM L7', 'VGO - Vergueiro - METRO L1',
       'VMD - Vila Madalena - METRO L2', 'VMN - Vila Mariana - METRO L1',
       'VOL - Vila Olimpia - CPTM L9',
       'VPA - Guilhermina Esperanca - METRO L3',
       'VPL - Vßrzea Paulista - CPTM L7', 'VPR - Vila Prudente - METRO L2',
       'VPT - Vila Prudente - METRO L15', 'VTD - Vila Matilde - METRO L3'],
      dtype='object', name='linha', length=1606)

In [ ]:
import seaborn as sns
import matplotlib
warnings.filterwarnings("ignore",category=matplotlib.cbook.mplDeprecation)

sns.set_style("white")
sns.set(rc={'figure.figsize':(13,8)})
sns.set(font_scale=1.3)

sns.distplot(diaLinha['BUT - Butanta - METRO L4'], label='Butantã')
sns.distplot(diaLinha['FAL - Faria Lima - METRO L4'], label='Faria Lima')
sns.distplot(diaLinha['FRA - Fradique Coutinho - METRO L4'], label='Fradique Coutinho')

plt.ylabel('Distribuição')
plt.xlabel('Embarques Dia Útil')
plt.legend()

In [ ]:
sns.distplot(diaLinha['LUZ - Luz - METRO L4'],label='Luz')
sns.distplot(diaLinha['PIN - Pinheiros - METRO L4'],label='Pinheiros')
sns.distplot(diaLinha['PTA - Paulista - METRO L4'],label='Paulista')
sns.distplot(diaLinha['REP - Republica - METRO L3'],label='República')
plt.ylabel('Distribuição')
plt.xlabel('Embarques Dia Útil')
plt.legend()

In [ ]:
print('Linha 1')
sns.set_palette("bright",n_colors=10)
sns.set(rc={'figure.figsize':(10,15)})
sns.set(style='white',font_scale=1.5)
sns.distplot(diaLinha['ANR - Ana Rosa - METRO L2'],label='ANR - Ana Rosa - METRO L2',vertical=True)
sns.distplot(diaLinha['BTO - Sao Bento - METRO L1'],label='BTO - Sao Bento - METRO L1',vertical=True)
sns.distplot(diaLinha['JAB - Jabaquara - METRO L1'],label='JAB - Jabaquara - METRO L1',vertical=True)
sns.distplot(diaLinha['JQM - Sao Joaquim - METRO L1'],label='JQM - Sao Joaquim - METRO L1',vertical=True)
sns.distplot(diaLinha['JUD - Sao Judas - METRO L1'],label='JUD - Sao Judas - METRO L1',vertical=True)
sns.distplot(diaLinha['LIB - Liberdade - METRO L1'],label='LIB - Liberdade - METRO L1',vertical=True)
sns.distplot(diaLinha['LUZ - Luz - METRO L1'],label='LUZ - Luz - METRO L1',vertical=True)
sns.distplot(diaLinha['PSE - Se - METRO L1'],label='PSE - Se - METRO L1',vertical=True)
sns.distplot(diaLinha['PSO - Paraiso - METRO L2'],label='PSO - Paraiso - METRO L2',vertical=True)
sns.distplot(diaLinha['SAN - Santana - METRO L1'],label='SAN - Santana - METRO L1',vertical=True)
sns.distplot(diaLinha['SAU - Saude - METRO L1'],label='SAU - Saude - METRO L1',vertical=True)
sns.distplot(diaLinha['SCZ - Santa Cruz - METRO L1'],label='SCZ - Santa Cruz - METRO L1',vertical=True)
sns.distplot(diaLinha['TTE - Tiete - METRO L1'],label='TTE - Tiete - METRO L1',vertical=True)
sns.distplot(diaLinha['TUC - Tucuruvi - METRO L1'],label='TUC - Tucuruvi - METRO L1',vertical=True)
sns.distplot(diaLinha['VGO - Vergueiro - METRO L1'],label='VGO - Vergueiro - METRO L1',vertical=True)
sns.distplot(diaLinha['VMN - Vila Mariana - METRO L1'],label='VMN - Vila Mariana - METRO L1',vertical=True)

plt.xlabel('Distribuição')
plt.ylabel('Embarques Dia Útil')
plt.legend()

In [31]:
estMetro = duv[duv.metro==1].linha.value_counts().index.values

estMetro

array(['PPQ - Armenia - METRO L1', 'IMG - Imigrantes - METRO L2',
       'SAU - Saude - METRO L1', 'PTA - Paulista - METRO L4',
       'LIB - Liberdade - METRO L1', 'PCA - Patriarca - METRO L3',
       'CNS -Consolacao - METRO L2', 'STA - Santo Amaro - METRO L5',
       'TTE - Tiete - METRO L1', 'PIG - Parada Inglesa - METRO L1',
       'DEO - Marechal Deodoro - METRO L3',
       'VPR - Vila Prudente - METRO L2', 'TTI - Tamanduatei - METRO L2',
       'LUZ - Luz - METRO L4', 'LUZ - Luz - METRO L1',
       'SAN - Santana - METRO L1', 'JUD - Sao Judas - METRO L1',
       'APN - Adolfo Pinheiro - METRO L5', 'ORT - Oratorio - METRO L15',
       'SAC - Sacoma - METRO L2', 'JQM - Sao Joaquim - METRO L1',
       'CKB - Chacara Klabin - METRO L2', 'JAB - Jabaquara - METRO L1',
       'TRD - Tiradentes - METRO L1', 'CON - Conceicao - METRO L1',
       'VBE - Vila das Belezas - METRO L5',
       'VMN - Vila Mariana - METRO L1',
       'FRA - Fradique Coutinho - METRO L4', 'BEL - Belem - METRO L3

In [ ]:
diaMetro = diaLinha[estMetro]
diaMetro.head()

# Distribuição do volume de embarques nos dias úteis - Linhas Metrô

In [ ]:
duvm = duv[duv.metro==1]
sns.set(rc={'figure.figsize':(12,8)},font_scale=1.2)
linha = 'Linha 1'
ranks = duvm[duvm.linha_trilho==linha].groupby('linha')['total_dia'].mean().fillna(0).sort_values()[::-1].index
print(linha)
sns.boxplot(x="linha", y="total_dia", data=duvm[duvm.linha_trilho==linha],order = ranks)
plt.xticks(rotation=90)

In [ ]:
linha = 'Linha 2'
ranks = duvm[duvm.linha_trilho==linha].groupby('linha')['total_dia'].mean().fillna(0).sort_values()[::-1].index
print(linha)
sns.boxplot(x="linha", y="total_dia", data=duvm[duvm.linha_trilho==linha],order = ranks)
plt.xticks(rotation=90)

In [ ]:
linha = 'Linha 3'
ranks = duvm[duvm.linha_trilho==linha].groupby('linha')['total_dia'].mean().fillna(0).sort_values()[::-1].index
print(linha)
sns.boxplot(x="linha", y="total_dia", data=duvm[duvm.linha_trilho==linha],order = ranks)
plt.xticks(rotation=90)

In [ ]:
linha = 'Linha 4'
ranks = duvm[duvm.linha_trilho==linha].groupby('linha')['total_dia'].mean().fillna(0).sort_values()[::-1].index
print(linha)
sns.boxplot(x="linha", y="total_dia", data=duvm[duvm.linha_trilho==linha],order = ranks)
plt.xticks(rotation=90)

In [ ]:
linha = 'Linha 5'
ranks = duvm[duvm.linha_trilho==linha].groupby('linha')['total_dia'].mean().fillna(0).sort_values()[::-1].index
print(linha)
sns.boxplot(x="linha", y="total_dia", data=duvm[duvm.linha_trilho==linha],order = ranks)
plt.xticks(rotation=90)

# Outliers

## Método 1: IQR por estação de Metrô

In [ ]:
from scipy.stats import iqr

def outliers_iqr(serieEstacao):
    iqrDemanda = iqr(serieEstacao,nan_policy='omit')
    quartile_1, quartile_3 = np.percentile(serieEstacao.dropna().values, [25, 75])
    lower_bound = quartile_1 - (iqrDemanda * 1.5)
    upper_bound = quartile_3 + (iqrDemanda * 1.5)
    return np.where((serieEstacao > upper_bound) | (serieEstacao < lower_bound))

diaLinha1 = diaLinha.copy(deep=True)

todosDiasOutliers = []
for est in estMetro:
    outliersDestaEstacao = outliers_iqr(diaLinha[est])
    print(est,outliersDestaEstacao)
    todosDiasOutliers.append(outliersDestaEstacao)    
    diaLinha1.loc[:,est] = 0
    diaLinha1.loc[diaLinha1.iloc[outliersDestaEstacao].index,est] = 1
    
todosDiasOutliers = np.unique(np.hstack(todosDiasOutliers))

In [39]:
diaLinha1[estacoes].to_csv('outliers metodo iqr.csv')

In [ ]:
diasNormais = np.setdiff1d(np.arange(0,len(diaLinha)),todosDiasOutliers)
diasNormais

In [ ]:
diaLinha.index = pd.to_datetime(diaLinha.index)
diaLinhaNormais = diaLinha.iloc[diasNormais]

print('Percentual de dias úteis válidos com este método:',len(diaLinhaNormais)/len(diasValidos)*100)

In [42]:
diaLinha.index

DatetimeIndex(['2016-05-17', '2016-05-18', '2016-05-19', '2016-05-20',
               '2016-05-23', '2016-05-24', '2016-05-25', '2016-05-30',
               '2016-05-31', '2016-06-01',
               ...
               '2018-06-18', '2018-06-19', '2018-06-20', '2018-06-21',
               '2018-06-22', '2018-06-25', '2018-06-26', '2018-06-27',
               '2018-06-28', '2018-06-29'],
              dtype='datetime64[ns]', name='dia', length=300, freq=None)

In [ ]:
plt.scatter(x=diaLinha.index,y=diaLinha['CON - Conceicao - METRO L1'],marker='o',label='Conceição L1',alpha=0.8)
plt.scatter(x=diaLinha.index,y=diaLinha['BUT - Butanta - METRO L4'],marker='o',label='Butantã L4',alpha=0.8)
plt.legend()

print('Comparativo estação Butantã vs Conceição: mesma mediana na série histórica')

In [ ]:
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['CON - Conceicao - METRO L1'],marker='o',label='Conceição L1',alpha=0.8)
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['BUT - Butanta - METRO L4'],marker='o',label='Butantã L4',alpha=0.8)
plt.legend()

print('Após o filtro pelo método do interquantile range com 1.5')
print('Comparativo estação Butantã vs Conceição: mesma mediana na série histórica')

In [ ]:
plt.scatter(x=diaLinha.index,y=diaLinha['FRA - Fradique Coutinho - METRO L4'],marker='o',label='Fradique',alpha=0.8)
plt.scatter(x=diaLinha.index,y=diaLinha['FAL - Faria Lima - METRO L4'],marker='o',label='Faria Lima',alpha=0.8)
plt.legend()

print('Comparativo estação Faria Lima e Fradique antes')

In [ ]:
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['FRA - Fradique Coutinho - METRO L4'],marker='o',label='Fradique',alpha=0.8)
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['FAL - Faria Lima - METRO L4'],marker='o',label='Faria Lima',alpha=0.8)
plt.legend()

print('Comparativo estação Faria Lima e Fradique depois dos filtros')

Resultado: apenas 17% dos dias são considerados normais, 83% dos dias seriam outliers devido à anormalidade de ao menos uma estação do sistema. 

Este método de IQR não considera nenhum dia outlier para a estação Butantã devido ao grande IQR.

Remove a maioria dos outliers da Butantã por existirem outras estações com outliers neste dia.

Remove todos os outliers da Faria Lima.

## Método 2: Zscore por estação

In [47]:
from scipy import stats

#Tira colunas com NaN (linhas que não comunicaram todo dia útil válido por algum motivo)
diaLinhaSemNan = diaLinha.loc[:,diaLinha.isnull().sum()==0]

#Verifica quais estações tem a série completa (tira inauguradas no período)
estacoesCompletas = np.intersect1d(estacoes,diaLinhaSemNan.columns)

diaLinhaEstacoesSemNan = diaLinhaSemNan[estacoesCompletas].copy(deep=True)

#Calcula o z index
z = np.abs(stats.zscore(diaLinhaEstacoesSemNan))

diasInvalidos = np.unique(np.where(z>3)[0])

In [48]:
diaLinhaEstacoesSemNan1 = diaLinhaEstacoesSemNan.copy(deep=True)
diaLinhaEstacoesSemNan1[:] = 0

for i,j in zip(np.where(z>2)[0],np.where(z>2)[1]):
    diaLinhaEstacoesSemNan1.loc[diaLinhaEstacoesSemNan1.iloc[i].name,diaLinhaEstacoesSemNan1.columns.values[j]] = 1

In [49]:
diaLinhaEstacoesSemNan1.to_csv('zscore2.csv')

In [50]:
diasNormais = np.setdiff1d(np.arange(0,len(diaLinha)),diasInvalidos)
diasNormais

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  47,  48,  49,  50,  51,  52,  53,  54,  55,
        56,  57,  58,  59,  60,  61,  62,  63,  64,  66,  68,  69,  70,
        71,  72,  73,  74,  76,  77,  78,  79,  80,  81,  82,  84,  86,
        87,  88,  89,  90,  92,  94,  95,  96,  97,  98,  99, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 115, 116, 117,
       118, 119, 120, 121, 122, 124, 125, 127, 128, 129, 130, 131, 132,
       134, 136, 137, 138, 139, 141, 153, 154, 156, 158, 161, 162, 163,
       166, 172, 173, 177, 179, 180, 184, 186, 189, 192, 193, 194, 195,
       196, 197, 199, 200, 201, 203, 207, 208, 210, 212, 213, 214, 215,
       217, 219, 220, 223, 224, 225, 226, 227, 228, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 241, 242, 245, 246, 247, 24

In [ ]:
diaLinhaEstacoesSemNan.head()

In [52]:
diaLinha.index = pd.to_datetime(diaLinha.index)
diaLinhaNormais = diaLinha.iloc[diasNormais]

print('Percentual de dias úteis válidos com este método:',len(diaLinhaNormais)/len(diasValidos)*100)

Percentual de dias úteis válidos com este método: 70.0


In [ ]:
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['CON - Conceicao - METRO L1'],marker='o',label='Conceição L1',alpha=0.8)
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['BUT - Butanta - METRO L4'],marker='o',label='Butantã L4',alpha=0.8)
plt.legend()

print('Após o filtro pelo método do zscore de 3')
print('Comparativo estação Butantã vs Conceição: mesma mediana na série histórica')

In [ ]:
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['FRA - Fradique Coutinho - METRO L4'],
            marker='o',label='Fradique',alpha=0.8)
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['FAL - Faria Lima - METRO L4'],
            marker='o',label='Faria Lima',alpha=0.8)
plt.legend()

print('Comparativo estação Faria Lima e Fradique depois dos filtros pelo método zscore de 3')

Vantagens:

Percentual de dias outliers é apenas 30%.

Desvantagens:

Não consegue captar a problemática da Estação Butantã. 

Melhor que o método IQR.

# Método 3: IsolationForest

In [ ]:
from sklearn.ensemble import IsolationForest

In [56]:
diaLinhaEstacoesSemNan.values

array([[1.7620e+04, 4.0639e+04, 7.4900e+03, ..., 3.6239e+04, 2.1690e+03,
        2.7387e+04],
       [1.6956e+04, 3.8776e+04, 9.9300e+03, ..., 3.4449e+04, 2.3560e+03,
        2.5324e+04],
       [1.7804e+04, 4.1286e+04, 9.7370e+03, ..., 3.5062e+04, 2.4860e+03,
        2.6939e+04],
       ...,
       [1.4385e+04, 2.8152e+04, 4.4460e+03, ..., 3.0716e+04, 1.1800e+02,
        2.4140e+04],
       [1.6393e+04, 3.4041e+04, 5.4390e+03, ..., 3.4593e+04, 4.9000e+01,
        2.6640e+04],
       [1.6277e+04, 3.3042e+04, 5.4890e+03, ..., 3.4489e+04, 2.7000e+01,
        2.7322e+04]])

In [57]:
#Split train test
from sklearn.model_selection import train_test_split
rnd = np.random.RandomState(42)
estacoesValores = diaLinhaEstacoesSemNan.values
blt_train, blt_test = train_test_split(estacoesValores, test_size=0.33, random_state=rnd)

print(blt_train)
print(blt_test)

[[17436. 38150.  9332. ... 34356.  2485. 27351.]
 [18036. 37983.  6551. ... 38803.  2098. 28285.]
 [17048. 38792.  8368. ... 36026.  2266. 27419.]
 ...
 [17385. 37577.  9327. ... 35762.  2655. 27081.]
 [18181. 38549.  6751. ... 39415.  2096. 28269.]
 [15121. 39227.  9199. ... 36552.  2732. 28271.]]
[[16765. 36434.  9284. ... 37191.  1937. 27769.]
 [17979. 37153.  6572. ... 38382.  1966. 28652.]
 [14311. 39992.  7885. ... 38462.  1844. 21969.]
 ...
 [18339. 39211. 10800. ... 39020.  1922. 27316.]
 [18894. 22328.  9194. ... 38393.  1829. 28705.]
 [18322. 37596.  6703. ... 39004.  2068. 28083.]]


In [58]:
#Aplica modelo IsolationForest
parametro=0.3
clf = IsolationForest(max_samples=100, random_state=rnd,contamination=parametro)
clf.fit(blt_train)
blt_pred_train = clf.predict(blt_train)
blt_pred_test = clf.predict(blt_test)

In [59]:
blt_pred_train

array([ 1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,  1,  1,  1,
       -1,  1,  1, -1,  1, -1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1, -1,  1,  1, -1,  1,  1, -1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1,
       -1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1,
        1, -1,  1, -1, -1, -1, -1,  1,  1,  1, -1,  1,  1, -1,  1,  1, -1,
       -1,  1, -1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,  1,
       -1,  1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1, -1,  1,  1,
       -1,  1,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1, -1, -1,  1,
       -1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1, -1])

In [60]:
blt_pred_test

array([ 1,  1, -1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1,
       -1, -1, -1,  1, -1,  1, -1,  1,  1,  1, -1, -1,  1, -1, -1, -1, -1,
        1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1,  1, -1,  1, -1, -1,  1,
       -1,  1, -1, -1, -1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1,  1, -1,
       -1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1,  1, -1,  1])

In [61]:
estPred = clf.predict(estacoesValores)

In [62]:
pd.DataFrame(estPred,columns=['classe'])['classe'].value_counts()

 1    205
-1     95
Name: classe, dtype: int64

In [63]:
diasOutliersIsolationForest = np.where(estPred==-1)[0]
diasOutliersIsolationForest

array([ 14,  16,  17,  22,  24,  25,  26,  27,  28,  29,  30,  31,  32,
        33,  75,  79,  81,  91,  93, 100, 101, 102, 111, 113, 114, 115,
       123, 127, 132, 138, 140, 141, 142, 143, 144, 145, 146, 147, 148,
       149, 150, 151, 152, 156, 157, 162, 164, 165, 166, 167, 169, 170,
       172, 174, 176, 191, 195, 196, 206, 209, 211, 213, 217, 218, 219,
       231, 234, 240, 243, 250, 252, 255, 262, 263, 264, 270, 272, 276,
       277, 278, 279, 282, 285, 286, 288, 289, 290, 291, 293, 294, 295,
       296, 297, 298, 299], dtype=int64)

In [64]:
diaLinhaEstacoesSemNan1 = diaLinhaEstacoesSemNan.copy(deep=True)
diaLinhaEstacoesSemNan1[:] = 0

for dia in diasOutliersIsolationForest:
    diaLinhaEstacoesSemNan1.loc[diaLinhaEstacoesSemNan1.iloc[dia].name,:] = 1

In [65]:
diaLinhaEstacoesSemNan1.to_csv('isolationForest_' + str(parametro) + '.csv')

In [66]:
diaLinhaNormais = diaLinha.iloc[diasOutliersIsolationForest]

print('Percentual de dias úteis válidos com este método:',len(diaLinhaNormais)/len(diasValidos)*100)

Percentual de dias úteis válidos com este método: 31.666666666666664


In [ ]:
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['CON - Conceicao - METRO L1'],marker='o',label='Conceição L1',alpha=0.8)
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['BUT - Butanta - METRO L4'],marker='o',label='Butantã L4',alpha=0.8)
plt.legend()

print('Após o filtro pelo método de IsolationForest')
print('Comparativo estação Butantã vs Conceição: mesma mediana na série histórica')

In [ ]:
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['FRA - Fradique Coutinho - METRO L4'],
            marker='o',label='Fradique',alpha=0.8)
plt.scatter(x=diaLinhaNormais.index,y=diaLinhaNormais['FAL - Faria Lima - METRO L4'],
            marker='o',label='Faria Lima',alpha=0.8)
plt.legend()

print('Comparativo estação Faria Lima e Fradique depois dos filtros pelo método de IsolationForest')

O método de IsolationForest usa todas as 63 variáveis para definir quais dias são outliers. Ele precisa de um parâmetro de entrada que é o percentual estimado de contaminação (presença de outliers). Mesmo colocando um percentual alto (40%), não é capaz de verificar individualmente cada estação.

In [69]:
duv

total_dia       dia      0     1     2      3      4       5       6  \
193315       913.0  20160517    NaN   NaN   NaN    NaN    9.0    76.0   137.0   
193316     13892.0  20160517   26.0   2.0   NaN    NaN   19.0   256.0   943.0   
193317     18422.0  20160517   30.0   2.0   NaN   14.0  271.0   757.0  1465.0   
193318      8823.0  20160517   29.0   NaN   NaN    NaN   18.0   208.0   617.0   
193319      2191.0  20160517    9.0   NaN   NaN    NaN   42.0   174.0   190.0   
193320     16201.0  20160517   34.0   2.0   NaN   21.0  284.0   711.0  1538.0   
193321      4462.0  20160517    NaN   NaN   NaN    NaN   19.0   238.0   416.0   
193322      2236.0  20160517   18.0   NaN   NaN    NaN   24.0   123.0   223.0   
193323      9298.0  20160517   42.0   1.0   NaN    NaN   85.0   323.0   818.0   
193324     14553.0  20160517   95.0   3.0   NaN   19.0  307.0   823.0  1302.0   
193325     21137.0  20160517   55.0  19.0   NaN    NaN  135.0   892.0  1763.0   
193326     10355.0  20160517   40.0  19.0   NaN    NaN   49.0   286.0   606.0   
193327       699.0  20160517    NaN   NaN   NaN    NaN    NaN     1.0    62.0   
193328      9481.0  20160517   14.0   NaN   NaN    NaN   40.0   239.0   649.0   
193329       853.0  20160517    NaN   NaN   NaN    NaN    NaN     NaN    91.0   
193330      5996.0  20160517    4.0   NaN   NaN    7.0   89.0   221.0   395.0   
193331       636.0  20160517    NaN   NaN   NaN    NaN    NaN    73.0   215.0   
193332       346.0  20160517    NaN   NaN   NaN    NaN    NaN    92.0   162.0   
193333     13886.0  20160517   19.0   NaN   NaN   11.0  290.0   780.0  1033.0   
193334     10521.0  20160517   18.0   NaN   NaN    NaN  145.0   481.0   905.0   
193335       633.0  20160517    NaN   NaN   NaN    NaN   26.0   195.0   258.0   
193336       486.0  20160517    NaN   NaN   NaN    NaN    NaN     NaN     NaN   
193337       260.0  20160517    NaN   NaN   NaN    NaN    NaN    41.0   173.0   
193338     15271.0  20160517   68.0   6.0   NaN    NaN  180.0   589.0  1287.0   
193339       177.0  20160517    NaN   NaN   NaN    NaN    NaN     5.0   169.0   
193340       283.0  20160517    NaN   NaN   NaN    NaN    NaN     NaN     NaN   
193341     13324.0  20160517   10.0   NaN   NaN    NaN  106.0   479.0   983.0   
193342      7827.0  20160517   11.0   NaN   NaN    NaN   50.0   271.0   755.0   
193343      1313.0  20160517    NaN   NaN   NaN    NaN   28.0    40.0    40.0   
193344      8075.0  20160517    NaN   NaN   NaN    NaN   21.0   256.0   627.0   
...            ...       ...    ...   ...   ...    ...    ...     ...     ...   
1294652    10897.0  20180629    4.0   NaN   NaN    2.0  335.0   887.0  1113.0   
1294653    13740.0  20180629    NaN   NaN   NaN   11.0  370.0   867.0  1532.0   
1294654     6243.0  20180629    1.0   NaN   NaN    NaN   87.0   304.0   435.0   
1294655      591.0  20180629    NaN   NaN   NaN    NaN   17.0    43.0   143.0   
1294656    10993.0  20180629    4.0   NaN   NaN    NaN    9.0    49.0   405.0   
1294657    15736.0  20180629    4.0   NaN   3.0  169.0  994.0  1565.0  1963.0   
1294658    39594.0  20180629  117.0   NaN   NaN   48.0  205.0   427.0   957.0   
1294659    58360.0  20180629   97.0   NaN   NaN    NaN  432.0  1895.0  3271.0   
1294660     7750.0  20180629   35.0  10.0   9.0   14.0  248.0   737.0   769.0   
1294661     5295.0  20180629    5.0   NaN   NaN    NaN   66.0   137.0   573.0   
1294662    11457.0  20180629   15.0   NaN   4.0    NaN   25.0   119.0   279.0   
1294663    38449.0  20180629   41.0   NaN   NaN    NaN   29.0   104.0   360.0   
1294664    34314.0  20180629   44.0   NaN   NaN    NaN  233.0  1137.0  2280.0   
1294665     5932.0  20180629    1.0   NaN   NaN    NaN   34.0   184.0   561.0   
1294666    53140.0  20180629   13.0   NaN  12.0    1.0  544.0  2805.0  6490.0   
1294667     4916.0  20180629    NaN   NaN   NaN    NaN  121.0   270.0   496.0   
1294668     5499.0  20180629    NaN   NaN   NaN    4.0   16.0    77.0   125.0   
1294669     3803.0  20180629    2.0   Na